### ISSUE TITLE
[add] GitHub Action 스크립트 작성

### ISSUE THREAD

**Issue by yaongmeow** [boostcampwm2023/iOS07-traveline#66]
## 📌  Issue

GitHub Action 스크립트를 작성합니다.

## ✅  To-do

- [x] GitHub Secret에 환경변수 등록
- [ ] `.yml` 파일 작성하기
- [ ] 테스트

**Comment by kmi0817** [comment]
수많은 머지... 그래도 배포 성공했습니다
